### ISSUE TITLE
napari-chatgpt is missing QT bindings

### ISSUE THREAD

**Issue by sporring** [royerlab/napari-chatgpt#17]
Hi, 

I'm really excited to try your plugin, however, following the instructions:
```
conda create -y -n napari-chatgpt -c conda-forge python=3.9
conda activate napari-chatgpt
pip install napari  
git clone https://github.com/royerlab/napari-chatgpt.git
cd napari-chatgpt
pip install -e .
```
The resulting napari program terminates with an error condition:
```
(napari-chatgpt) jrh630@SCI1012515 napari-chatgpt % napari
Traceback (most recent call last):
  File "/Users/jrh630/anaconda3/envs/napari-chatgpt/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/jrh630/anaconda3/envs/napari-chatgpt/lib/python3.9/site-packages/napari/__main__.py", line 554, in main
    _maybe_rerun_with_macos_fixes()
  File "/Users/jrh630/anaconda3/envs/napari-chatgpt/lib/python3.9/site-packages/napari/__main__.py", line 453, in _maybe_rerun_with_macos_fixes
    from qtpy import API_NAME
  File "/Users/jrh630/anaconda3/envs/napari-chatgpt/lib/python3.9/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
(napari-chatgpt) jrh630@SCI1012515 napari-chatgpt % git rev-parse FETCH_HEAD
FETCH_HEAD
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
I'm on a macbook pro m1 chip, macos Ventura 13.5, and today's version napari-chatgpt:
```
(napari-chatgpt) jrh630@SCI1012515 napari-chatgpt % git rev-parse FETCH_HEAD
734cf7d137a5e1f1ab8ff7ae586cee0ab739e43f
```
Napari-chatpgt runs with the default non-cloned version, without gpt4 unfortunately, see other issue-ticket.

Thanks, Jon

**Comment by royerloic** [comment]
Hi Jon,

In general,  you want to install napari this way:


```
python -m pip install "napari[all]"
```

But on a MAC M1, that won't work, you need to do this:

```
conda install -c conda-forge napari pyqt
conda update napari
conda install -c conda-forge napari pyside2
```

Once you confirm that napari works in your environment, you can install Omega...
Should work, let me know if you still face issues...
