### ISSUE TITLE
Unable to run Napari after installing napari-chatgpt

### ISSUE THREAD

**Issue by rajpiyush18** [royerlab/napari-chatgpt#44]
Hello,

I am unable to run Napari after installing napari-chatgpt.

I am getting the following error:
-------------------------
Traceback (most recent call last):
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\plato\anaconda3\envs\napari_env\Scripts\napari.exe\__main__.py", line 4, in <module>
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\site-packages\napari\__main__.py", line 17, in <module>
    from napari.utils.translations import trans
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\site-packages\napari\utils\__init__.py", line 8, in <module>
    from napari.utils.notebook_display import nbscreenshot
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\site-packages\napari\utils\notebook_display.py", line 9, in <module>
    from lxml.html.clean import Cleaner
  File "C:\Users\plato\anaconda3\envs\napari_env\lib\site-packages\lxml\html\clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
------------------------------------------------------

I tried making new environment and reinstalling, but that is not solving the issue

**Comment by rajpiyush18** [comment]
The following installation solved my issue:

pip install --upgrade lxml_html_clean
